name: DEMO ARTIFACT

on: push

jobs:
  job1:
  name: upload ARTIFACT
  runs-on: ubuntu-latest
  steps:
   - name: "create local"
     run: echo "u have to run these boys" > files.txt
    
     uses: actions/upload-artifact@v2
     with:
     name: file
     path: files.txt


  job2:
  name: download ARTIFACT
  runs-on: ubuntu-latest
  needs: job1
  steps:
  
  uses: actions/download-artifact@v2
  with:
    name: file
  run: cat files.txt

